.EditorConfig
- 유니티 내 cs파일 생성 시 UTF-8 자동 인코딩 되는 파일 추가
=> [💡Feature] 인코딩 파일 추가

IdleGame/Assets/Resources/Prefabs/EnemyFrame.prefab, IdleGame/Assets/Resources/Prefabs/EnemyFrame.prefab.meta, IdleGame/Assets/Resources/Prefabs/EnemyProjectileFrame.prefab, IdleGame/Assets/Resources/Prefabs/EnemyProjectileFrame.prefab.meta, IdleGame/Assets/Resources/Prefabs/EnemyProjectileVFXTest.prefab, IdleGame/Assets/Resources/Prefabs/EnemyProjectileVFXTest.prefab.meta, IdleGame/Assets/Resources/ScriptableObjects/TestEnemy.asset, IdleGame/Assets/Scenes/TestScenes/KDH_Test_Scene.unity, IdleGame/Assets/Scripts/@Test/TestSceneKDH.cs, IdleGame/Assets/Scripts/@Test/TestSceneKDH.cs.meta, IdleGame/Assets/Scripts/Enemy.meta, IdleGame/Assets/Scripts/Enemy/BaseEnemy.cs, IdleGame/Assets/Scripts/Enemy/BaseEnemy.cs.meta, IdleGame/Assets/Scripts/Enemy/ProjectileHandler.cs, IdleGame/Assets/Scripts/Enemy/ProjectileHandler.cs.meta, IdleGame/Assets/Scripts/ScriptableObjects/EnemyBlueprint.cs
+ 몬스터의 기초적인 이동, 공격을 하는 BaseEnemy Class 추가
+ 발사체를 조작하는 ProjectileHandler Class를 추가
=> [💡Feature] BaseEnemy, ProjectileHandler

IdleGame/Assets/Scripts/Main/Model/Player.cs
=> [🛠️Fix] Player Attack Logic

IdleGame/Assets/Resources/Prefabs/Model/EnemyFrame.prefab, IdleGame/Assets/Resources/Prefabs/Model/PlayerFrame.prefab, IdleGame/Assets/Scenes/TestScenes/KDH_Test_Scene.unity, IdleGame/Assets/Scripts/Main/Model/Enemy/BaseEnemy.cs, IdleGame/Assets/Scripts/Main/Model/Player.cs
+ 플레이어 HP 바
+ 플레이어 초당 체력 재생
+ 플레이어 크리티컬 공격
+ 몬스터 처치 시 플레이어 골드 추가
=> [➕Add] Player function add

IdleGame/Assets/Scripts/Core/NumUnit.cs, IdleGame/Assets/Scripts/Core/NumUnit.cs.meta, IdleGame/Assets/Scripts/Main/Model/Player.cs
=> [💡Feature] number unit bundling

IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_1.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_2.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_3.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_4.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_5.asset, IdleGame/Assets/Resources/ScriptableObjects/Test_Boss_1.asset, IdleGame/Assets/Resources/ScriptableObjects/Test_Boss_1.asset.meta, IdleGame/Assets/Scripts/@Test/TestSceneHSB.cs, IdleGame/Assets/Scripts/Main/Model/Enemy/BaseEnemy.cs, IdleGame/Assets/Scripts/Main/Model/Player.cs, IdleGame/Assets/Scripts/Managers/StageManager.cs, IdleGame/Assets/Scripts/ScriptableObjects/StageBlueprint.cs
=> Merge Hsb stage

IdleGame/Assets/Resources/Prefabs/UI/Canvas_FloatingDamage.prefab, IdleGame/Assets/Resources/Prefabs/UI/UIPopupEquipment.prefab, IdleGame/Assets/Resources/Prefabs/UI/UISceneMain.prefab, IdleGame/Assets/Resources/ScriptableObjects/Items.meta
=> [➕Add] Equip UI

IdleGame/Assets/Scripts/Main/Model/Enemy/ProjectileHandlerBase.cs
+발사체가 충돌되지 않았을때 사라지게 하기 위해 수명 주기를 설정
=> [🐛BugFix] Projectile Life Cycle Add

IdleGame/Assets/Resources/Prefabs/UI/Btn_ResourceUse.prefab, IdleGame/Assets/Resources/Prefabs/UI/Btn_ResourceUse.prefab.meta, IdleGame/Assets/Resources/Prefabs/UI/Shop_Summon.prefab, IdleGame/Assets/Resources/Prefabs/UI/Shop_Summon.prefab.meta, IdleGame/Assets/Resources/Prefabs/UI/SummonBanner.prefab, IdleGame/Assets/Resources/Prefabs/UI/SummonBanner.prefab.meta, IdleGame/Assets/Scripts/ScriptableObjects/SummonBlueprint.cs, IdleGame/Assets/Scripts/ScriptableObjects/SummonBlueprint.cs.meta, IdleGame/Assets/Scripts/UI/Popup/UIPopupOptionDropdownPanel.cs, IdleGame/Assets/Scripts/UI/Popup/UIPopupShopSummon.cs, IdleGame/Assets/Scripts/UI/Popup/UIPopupShopSummon.cs.meta
- 상점 페이지 중 소환 페이지 추가
- 임시로 게임 정보 메뉴 버튼에 연결
=> Merge HSB Branch

IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_1.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_2.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_4.asset, IdleGame/Assets/Resources/ScriptableObjects/Stages/StageConfig_5.asset, IdleGame/Assets/Scripts/Data/GameUserProfile.cs, IdleGame/Assets/Scripts/Data/StatInfo.cs, IdleGame/Assets/Scripts/Main/Model/Player/Player.cs, IdleGame/Assets/Scripts/Managers/DataManager.cs, IdleGame/Assets/Scripts/Managers/GameManager.cs, IdleGame/Assets/Scripts/Managers/SessionManager.cs, IdleGame/Assets/Scripts/Managers/StageManager.cs, IdleGame/Assets/Scripts/UI/Elements/UIUpgradeStat.cs, IdleGame/Assets/Scripts/UI/Scene/UISceneMain.cs
- 데이터 업데이트 구현 =>그러나 데이터 업뎃 소스 관리 필요로 잠시 주석처리
- 스테이지 매니저 수정
=> [➕Add] Firestore Data Update

IdleGame/Assets/Scripts/UI/Notificate/EquipmentPopupNotificate.cs, IdleGame/Assets/Scripts/UI/Notificate/ReinforceArmorTypeItemNotificate.cs, IdleGame/Assets/Scripts/UI/Notificate/ReinforceWeaponTypeItemNotificate.cs
+ 게임 종료 시, notificate manager가 먼저 파괴되어 Null Reference Exception 오류 뜨던 것을 수정
=> [🐛BugFix] notificate manager NullReferenceException fix

IdleGame/Assets/@Resources/Prefabs/UI/UISceneMain.prefab, IdleGame/Assets/Scripts/Managers/NotificateManager.cs, IdleGame/Assets/Scripts/UI/Notificate/NotificateRecommendArmorItemSlot.cs, IdleGame/Assets/Scripts/UI/Notificate/NotificateRecommendWeaponItemSlot.cs
+ 아이템이 하나도 없어도 오류가 발생되지 않도록 수정
+ 코드 수정
=> [🛠️Fix] Notificate Logic Fix

IdleGame/Assets/@Resources/Blueprints/Items/ItemDataContainer.asset, IdleGame/Assets/@Resources/Blueprints/Skill/SkillDataContainer.asset, IdleGame/Assets/@Resources/Blueprints/Skill/SkillDataContainer.asset.meta, IdleGame/Assets/@Resources/Prefabs/UI/UISceneMain.prefab, IdleGame/Assets/AddressableAssetsData/AssetGroups/Blueprints.asset, IdleGame/Assets/Scripts/Main/Player/PlayerSkillHandler.cs, IdleGame/Assets/Scripts/Main/Skill/BaseSkill.cs, IdleGame/Assets/Scripts/Main/Skill/FireBallProjectile.cs, IdleGame/Assets/Scripts/Main/Skill/MeteorProjectile.cs, IdleGame/Assets/Scripts/Managers/DataManager.cs, IdleGame/Assets/Scripts/Managers/InventoryManager.cs, IdleGame/Assets/Scripts/Managers/SkillDataManager.cs, IdleGame/Assets/Scripts/ScriptableObjects/ItemContainerBlueprint.cs, IdleGame/Assets/Scripts/ScriptableObjects/SkillBlueprint.cs, IdleGame/Assets/Scripts/ScriptableObjects/SkillContainerBlueprint.cs, IdleGame/Assets/Scripts/ScriptableObjects/SkillContainerBlueprint.cs.meta, IdleGame/Assets/Scripts/UI/Elements/UseSkill/UIUseSkillSlots.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkill.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillDetail.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillSlotsEquip.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillSlotsInven.cs
+각각 스킬 SO로 지정되어있던 것을 Skill Container하나로 통합
=> [🛠️Fix] Skill Container

IdleGame/Assets/@Resources/Blueprints/Items/ItemDataContainer.asset, IdleGame/Assets/@Resources/Blueprints/Skill/SkillDataContainer.asset
=> [🛠️Fix] item SO Data fix

IdleGame/Assets/Scripts/Core/Enums.cs, IdleGame/Assets/Scripts/Main/Player/Player.cs, IdleGame/Assets/Scripts/Main/Player/PlayerSkillHandler.cs, IdleGame/Assets/Scripts/Main/Player/PlayerStateController.cs, IdleGame/Assets/Scripts/Main/Player/PlayerStateController.cs.meta
=> [🛠️Fix] player state logic fix

IdleGame/Assets/@Resources/Blueprints/Container/ItemDataContainer.asset, IdleGame/Assets/Scripts/Core/Enums.cs, IdleGame/Assets/Scripts/Main/Enemy/BaseEnemy.cs, IdleGame/Assets/Scripts/Main/Skill/BaseSkill.cs, IdleGame/Assets/Scripts/Main/Skill/ChainLight.cs, IdleGame/Assets/Scripts/Main/Skill/RainbowLight.cs
+일부 스킬 로직 변경
+뷰포트 외부 적 데미지를 입지 않도록 수정
+장비 테스트 스탯 임시 추가
=> [🛠️Fix] Skill, enemy Damage Logic / Equipment Test Stats Add

IdleGame/Assets/@Resources/Prefabs/UI/Scene/UISceneMain.prefab, IdleGame/Assets/Pixel Arsenal/Prefabs/Environment/Sparkle/SparklePurple.prefab, IdleGame/Assets/Pixel Arsenal/Prefabs/Environment/Sparkle/SparkleYellow.prefab, IdleGame/Assets/Scripts/Core/Utilities.cs, IdleGame/Assets/Scripts/Managers/DataManager.cs, IdleGame/Assets/Scripts/Managers/FollowerDataManager.cs, IdleGame/Assets/Scripts/Managers/InventoryManager.cs, IdleGame/Assets/Scripts/Managers/NotificateManager.cs, IdleGame/Assets/Scripts/Managers/SkillDataManager.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Equipment/UIPopupEquipSlots.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Equipment/UIPopupEquipment.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Follower/UIPopupFollowerDetail.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Follower/UIPopupFollowerSlotsInven.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillDetail.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillSlotsInven.cs
+ 레벨 제한 추가
+ 100레벨에서 강화 시, 다음 레벨 아이템으로 넘어감
=> [💡Feature] Item Level Limit

IdleGame/Assets/Scripts/Managers/SummonManager.cs, IdleGame/Assets/Scripts/Managers/SummonManagerInit.cs, IdleGame/Assets/Scripts/UI/Popup/UIPopupRewardsSummon.cs
=> [➕Add] Summon Repeat Add

IdleGame/Assets/@Resources/Prefabs/UI/Popup/UIPopupRewardsSummon.prefab, IdleGame/Assets/@Resources/Prefabs/UI/Scene/UISceneMain.prefab, IdleGame/Assets/Scripts/Managers/SummonManager.cs, IdleGame/Assets/Scripts/UI/Popup/UIPopupRewardsSummon.cs
=> Merge Hsb dev

IdleGame/Assets/@Resources/Prefabs/UI/Popup/UIPopupSkill.prefab, IdleGame/Assets/@Resources/Prefabs/UI/Scene/UISceneMain.prefab, IdleGame/Assets/@Resources/Sprites/Images/UI/rpg-items.png.meta, IdleGame/Assets/Scripts/Managers/SkillDataManager.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkill.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillSlotContainerEquip.cs, IdleGame/Assets/Scripts/UI/Popup/Player/Skill/UIPopupSkillSlotsEquip.cs
+스킬 장착 해제 시 스킬 오브젝트와 스크립트가 정상적으로 제거되도록 수정
+스킬 교체 시 장착 UI가 정상적으로 출력되도록 수정
=> [🐛BugFix] skill bug fix
